//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ahaley.AtTask.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ahaley.AtTask.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;data&quot;: [
        ///  {
        ///  &quot;ID&quot;: &quot;4d8cb6ee000c6d0820ca981bfebc8c20&quot;,
        ///  &quot;objCode&quot;: &quot;EXPNS&quot;,
        ///  &quot;actualUnitAmount&quot;: 2,
        ///  &quot;parameterValues&quot;: {
        ///  &quot;DE:Contractor Company&quot;: &quot;NA&quot;,
        ///  &quot;DE:Expense Owner&quot;: &quot;9d3c8120a653cebbe040007f01002438&quot;},
        ///  &quot;expenseTypeID&quot;: &quot;9d3c90342fe3fa2ae040007f01002426&quot;},
        ///  {
        ///  &quot;ID&quot;: &quot;4d8cb55f000c534aeaa6ff93dd4dc8c1&quot;,
        ///  &quot;objCode&quot;: &quot;EXPNS&quot;,
        ///  &quot;actualUnitAmount&quot;: 2,
        ///  &quot;parameterValues&quot;: {
        ///  &quot;DE:Contractor Company&quot;: &quot;NA&quot;,
        ///  &quot;DE:Expense Owner&quot;: &quot;9d3c8120a653cebbe040007f01002438&quot;},
        ///  &quot;expe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string expenses {
            get {
                return ResourceManager.GetString("expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { &quot;data&quot;: {
        ///&quot;ID&quot;: &quot;9d3c81203f3ecebbe040007f01002438&quot;,
        ///&quot;objCode&quot;: &quot;TSHET&quot;,
        ///&quot;userID&quot;: &quot;9d3c8120a643cebbe040007f01002438&quot;,
        ///&quot;regularHours&quot;: 40,
        ///&quot;hours&quot;: [
        ///{
        ///&quot;ID&quot;: &quot;9d3cae77622cc90ce040007f0100241e&quot;,
        ///&quot;objCode&quot;: &quot;HOUR&quot;,
        ///&quot;hours&quot;: 1,
        ///&quot;hourTypeID&quot;: &quot;ca57688b54c3a0375c408f3ccf0af28b&quot;},
        ///{
        ///&quot;ID&quot;: &quot;9d3cae7762abc90ce040007f0100241e&quot;,
        ///&quot;objCode&quot;: &quot;HOUR&quot;,
        ///&quot;hours&quot;: 1,
        ///&quot;hourTypeID&quot;: &quot;ca57688b54c3a0375c408f3ccf0af28b&quot;},
        ///{
        ///&quot;ID&quot;: &quot;9d3cae7762ddc90ce040007f0100241e&quot;,
        ///&quot;objCode&quot;: &quot;HOUR&quot;,
        ///&quot;hours&quot;: 0.5,
        ///&quot;hourTypeID&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string timesheet {
            get {
                return ResourceManager.GetString("timesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { &quot;data&quot;: [
        ///{
        ///&quot;ID&quot;: &quot;9d3c81203e1bcebbe040007f01002438&quot;,
        ///&quot;objCode&quot;: &quot;TSHET&quot;,
        ///&quot;userID&quot;: &quot;9d3c8120a63bcebbe040007f01002438&quot;,
        ///&quot;regularHours&quot;: 0,
        ///&quot;hours&quot;: [
        ///],
        ///&quot;endDate&quot;: &quot;2010-12-26T02:00:00:000-0500&quot;,
        ///&quot;overtimeHours&quot;: 0,
        ///&quot;totalHours&quot;: 0,
        ///&quot;user&quot;: {
        ///&quot;ID&quot;: &quot;9d3c8120a63bcebbe040007f01002438&quot;,
        ///&quot;name&quot;: &quot;David Goodwyn&quot;,
        ///&quot;objCode&quot;: &quot;USER&quot;,
        ///&quot;lastName&quot;: &quot;Goodwyn&quot;,
        ///&quot;firstName&quot;: &quot;David&quot;}},
        ///{
        ///&quot;ID&quot;: &quot;9d3c81203f12cebbe040007f01002438&quot;,
        ///&quot;objCode&quot;: &quot;TSHET&quot;,
        ///&quot;userID&quot;: &quot;9d3c8120a611cebbe040007f01002438&quot;,
        ///&quot;re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string timesheets {
            get {
                return ResourceManager.GetString("timesheets", resourceCulture);
            }
        }
    }
}
